src/Plugins/Plugin.Widget.GoogleAnalytics/Controllers/GoogleAnalyticsController.cs
using BeYourMarket.Core.Web;
using BeYourMarket.Service;
using Repository.Pattern.UnitOfWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Plugin.Widget.GoogleAnalytics.Controllers
{
    public class GoogleAnalyticsController : Controller
    {
        private readonly ISettingDictionaryService _settingDictionaryService;
        private readonly DataCacheService _dataCacheService;
        private readonly IUnitOfWorkAsync _unitOfWorkAsync;

        public GoogleAnalyticsController(
            ISettingDictionaryService settingDictionaryService,
            IUnitOfWorkAsync unitOfWorkAsync,
            DataCacheService dataCacheService)
        {
            _settingDictionaryService = settingDictionaryService;
            _unitOfWorkAsync = unitOfWorkAsync;
            _dataCacheService = dataCacheService;
        }

        #region FrontEnd Method
        /// <summary>
        /// Frontend
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            var setting = BeYourMarket.Service.CacheHelper.GetSettingDictionary(GoogleAnalyticsPlugin.SettingTrackingID);

            if (setting == null)
                return new EmptyResult();

            return View("~/Plugins/Plugin.Widget.GoogleAnalytics/Views/Index.cshtml", setting);
        }
        #endregion

        #region Admin Method
        public ActionResult Configure()
        {
            var model = _settingDictionaryService.GetSettingDictionary(CacheHelper.Settings.ID, GoogleAnalyticsPlugin.SettingTrackingID);
            return View("~/Plugins/Plugin.Widget.GoogleAnalytics/Views/Configure.cshtml", model);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public async Task<ActionResult> Configure(string trackingID)
        {
            var settingExisting = _settingDictionaryService.GetSettingDictionary(CacheHelper.Settings.ID, GoogleAnalyticsPlugin.SettingTrackingID);
            settingExisting.Value = trackingID;

            _settingDictionaryService.SaveSettingDictionary(settingExisting);

            await _unitOfWorkAsync.SaveChangesAsync();

            _dataCacheService.RemoveCachedItem(CacheKeys.SettingDictionary);

            TempData[TempDataKeys.UserMessage] = "[[[Plugin updated!]]]";

            return RedirectToAction("Plugins", "Plugin", new { area = "Admin" });
        }
        #endregion
    }
}

src/Plugins/Plugin.Widget.GoogleAnalytics/Views/Configure.cshtml
@model BeYourMarket.Model.Models.SettingDictionary

@{
    ViewBag.Title = "Settings";
}

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title">Configure Google Analytics</h3></div>
            <div class="panel-body">
                <form action="@Url.Action("Configure", "GoogleAnalytics")" id="settingsForm" method="post" class="form-horizontal" role="form">

                    @Html.HiddenFor(x => x.ID)

                    <div class="form-group">
                        <label class="col-md-2 control-label">TrackingID</label>
                        <div class="col-md-10">
                            <input type="text" class="form-control" id="trackingID" name="trackingID" value="@Model.Value" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-offset-2 col-lg-10">
                            <button class="btn btn-primary" type="submit"><i class="fa fa-save"></i> Save</button>
                            <a href="@Url.Action("Plugins", "Plugin", new { area = "Admin" })" class="btn btn-default"><i class="fa fa-remove"></i> Cancel</a>
                        </div>
                    </div>

                </form>
            </div>

        </div>
    </div>
</div>

src/Plugins/Plugin.Widget.GoogleAnalytics/Views/Index.cshtml
@model BeYourMarket.Model.Models.SettingDictionary

@{
    Layout = "";
}

@if (!string.IsNullOrEmpty(Model.Value))
{
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', '@Model.Value', 'auto');
        ga('send', 'pageview');

    </script>
}