src/Plugins/Plugin.Payment.Stripe/Controllers/PaymentStripeController.cs
using BeYourMarket.Core.Web;
using BeYourMarket.Model.Enum;
using BeYourMarket.Service;
using Plugin.Payment.Models;
using Repository.Pattern.UnitOfWork;
using Stripe;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using RestSharp;
using BeYourMarket.Core.Controllers;
using Plugin.Payment.Stripe.Models;
using Plugin.Payment.Stripe.Models.Grids;
using Plugin.Payment.Services;
using Plugin.Payment.Stripe.Data;
using Microsoft.Practices.Unity;
using BeYourMarket.Service.Models;
using i18n;

namespace Plugin.Payment.Stripe.Controllers
{
    public class PaymentStripeController : Controller, IPaymentController
    {
        private readonly ISettingDictionaryService _settingDictionaryService;
        private readonly DataCacheService _dataCacheService;
        private readonly IUnitOfWorkAsync _unitOfWorkAsync;
        private readonly IOrderService _orderService;

        private readonly IStripeTransactionService _transactionService;
        private readonly IStripeConnectService _stripConnectService;
        private readonly IUnitOfWorkAsync _unitOfWorkAsyncStripe;

        public PaymentStripeController(
            ISettingDictionaryService settingDictionaryService,
            IUnitOfWorkAsync unitOfWorkAsync,
            DataCacheService dataCacheService,
            IOrderService orderService,
            IStripeTransactionService transationService,
            IStripeConnectService stripConnectService,
            [Dependency("unitOfWorkStripe")] IUnitOfWorkAsync unitOfWorkAsyncStripe)
        {
            _settingDictionaryService = settingDictionaryService;
            _unitOfWorkAsync = unitOfWorkAsync;
            _dataCacheService = dataCacheService;

            _orderService = orderService;

            _transactionService = transationService;
            _stripConnectService = stripConnectService;
            _unitOfWorkAsyncStripe = unitOfWorkAsyncStripe;
        }

        #region FrontEnd Method
        /// <summary>
        /// Frontend
        /// </summary>
        /// <returns></returns>
        public ActionResult Payment(BeYourMarket.Model.Models.Order additionalData)
        {
            return View("~/Plugins/Plugin.Payment.Stripe/Views/Payment.cshtml", additionalData);
        }

        [HttpPost]
        public async Task<ActionResult> Payment(int id, string stripeToken, string stripeEmail)
        {
            var selectQuery = await _orderService.Query(x => x.ID == id).Include(x => x.Listing).SelectAsync();

            // Check if order exists
            var order = selectQuery.FirstOrDefault();
            if (order == null)
                return new HttpNotFoundResult();

            var stripeConnectQuery = await _stripConnectService.Query(x => x.UserID == order.UserProvider).SelectAsync();
            var stripeConnect = stripeConnectQuery.FirstOrDefault();

            if (stripeConnect == null)
                return new HttpNotFoundResult();

            //https://stripe.com/docs/checkout
            var charge = new StripeChargeCreateOptions();

            // always set these properties
            charge.Amount = order.PriceInCents;
            charge.Currency = CacheHelper.Settings.Currency;
            charge.Source = new StripeSourceOptions()
            {
                TokenId = stripeToken
            };

            // set booking fee
            var bookingFee = (int)Math.Round(CacheHelper.Settings.TransactionFeePercent * order.PriceInCents);
            if (bookingFee < CacheHelper.Settings.TransactionMinimumFee * 100)
                bookingFee = (int)(CacheHelper.Settings.TransactionMinimumFee * 100);

            charge.ApplicationFee = bookingFee;
            charge.Capture = false;
            charge.Description = order.Description;
            charge.Destination = stripeConnect.stripe_user_id;
            var chargeService = new StripeChargeService(CacheHelper.GetSettingDictionary("StripeApiKey").Value);
            StripeCharge stripeCharge = chargeService.Create(charge);

            // Update order status
            order.Status = (int)Enum_OrderStatus.Pending;
            order.PaymentPlugin = StripePlugin.PluginName;
            _orderService.Update(order);

            // Save transaction
            var transaction = new StripeTransaction()
            {
                OrderID = id,
                ChargeID = stripeCharge.Id,
                StripeEmail = stripeEmail,
                StripeToken = stripeToken,
                Created = DateTime.Now,
                LastUpdated = DateTime.Now,
                FailureCode = stripeCharge.FailureCode,
                FailureMessage = stripeCharge.FailureMessage,
                ObjectState = Repository.Pattern.Infrastructure.ObjectState.Added
            };

            _transactionService.Insert(transaction);

            await _unitOfWorkAsync.SaveChangesAsync();
            await _unitOfWorkAsyncStripe.SaveChangesAsync();

            ClearCache();

            // Payment succeeded
            if (string.IsNullOrEmpty(stripeCharge.FailureCode))
            {
                // Send message to the user
                var message = new MessageSendModel()
                {
                    UserFrom = order.UserReceiver,
                    UserTo = order.UserProvider,
                    Subject = order.Listing.Title,
                    ListingID = order.ListingID,
                    Body = HttpContext.ParseAndTranslate(string.Format(
                    "[[[Order Requested - %0 - Total Price %1 %2. <a href=\"%3\">See Details</a>|||{0}|||{1}|||{2}|||{3}]]]",
                    order.Description,
                    order.Price,
                    order.Currency,
                    Url.Action("Orders", "Payment")))
                };

                await MessageHelper.SendMessage(message);

                TempData[TempDataKeys.UserMessage] = "[[[Thanks for your order! You payment will not be charged until the provider accepted your request.]]]";
                return RedirectToAction("Orders", "Payment");
            }
            else
            {
                TempData[TempDataKeys.UserMessageAlertState] = "bg-danger";
                TempData[TempDataKeys.UserMessage] = stripeCharge.FailureMessage;

                return RedirectToAction("Payment");
            }
        }

        private void ClearCache()
        {
            Response.Cache.SetCacheability(HttpCacheability.NoCache);
            Response.Cache.SetExpires(DateTime.UtcNow.AddHours(-1));
            Response.Cache.SetNoStore();
        }

        public ActionResult PaymentSettingDeauthorize()
        {
            var userId = User.Identity.GetUserId();
            var stripeConnectQuery = _stripConnectService.Query(x => x.UserID == userId).Select();
            var stripeConnect = stripeConnectQuery.FirstOrDefault();

            // Delete old one and insert new one
            if (stripeConnect != null)
                _stripConnectService.Delete(stripeConnect);

            var client = new RestClient("https://connect.stripe.com/oauth/deauthorize");

            var request = new RestRequest(Method.POST);
            request.AddParameter("client_secret", CacheHelper.GetSettingDictionary("StripeApiKey").Value);
            request.AddParameter("client_id", CacheHelper.GetSettingDictionary("StripeClientID").Value);
            request.AddParameter("stripe_user_id", stripeConnect.stripe_user_id);

            var response = client.Execute(request);

            _unitOfWorkAsyncStripe.SaveChanges();

            TempData[TempDataKeys.UserMessage] = "[[[Disconnnect to stripe successfully!]]]";

            return RedirectToAction("PaymentSetting", "Payment", new { area = "" });
        }

        public ActionResult PaymentSetting(string scope, string code)
        {
            if (!string.IsNullOrEmpty(scope) && !string.IsNullOrEmpty(code))
            {
                var client = new RestClient("https://connect.stripe.com/oauth/token");
                var request = new RestRequest(Method.POST);
                request.AddParameter("client_secret", CacheHelper.GetSettingDictionary("StripeApiKey").Value);
                request.AddParameter("code", code);
                request.AddParameter("grant_type", "authorization_code");

                var response = client.Execute<StripeConnect>(request);

                if (string.IsNullOrEmpty(response.Data.error))
                {
                    var userId = User.Identity.GetUserId();
                    var stripeConnectQuery = _stripConnectService.Query(x => x.UserID == userId).Select();
                    var stripeConnect = stripeConnectQuery.FirstOrDefault();

                    // Delete old one and insert new one
                    if (stripeConnect != null)
                        _stripConnectService.Delete(stripeConnect);

                    response.Data.UserID = User.Identity.GetUserId();
                    response.Data.Created = DateTime.Now;
                    response.Data.LastUpdated = DateTime.Now;
                    response.Data.ObjectState = Repository.Pattern.Infrastructure.ObjectState.Added;

                    _stripConnectService.Insert(response.Data);
                    _unitOfWorkAsyncStripe.SaveChanges();

                    TempData[TempDataKeys.UserMessage] = "[[[Connnect to stripe successfully!]]]";

                    return View("~/Plugins/Plugin.Payment.Stripe/Views/PaymentSetting.cshtml", Plugin.Payment.Stripe.StripePlugin.Enum_StripeConnectStatus.Authorized);
                }
                else
                {
                    TempData[TempDataKeys.UserMessageAlertState] = "bg-danger";
                    TempData[TempDataKeys.UserMessage] = response.Data.error_description;
                }
            }
            else
            {

src/Plugins/Plugin.Payment.Stripe/Views/Configure.cshtml
@model Plugin.Payment.Models.PaymentSettingModel
@{
    ViewBag.Title = "Payment Settings";
}

<div class="row">
    <div class="col-md-12">
        <form action="@Url.Action("Configure", "PaymentStripe")" id="settingsForm" method="post" class="form-horizontal" role="form">
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    Payment Settings
                </div>
                <div class="panel-body">
                    <h4>
                        <i class="fa fa-cc-stripe"></i> Stripe Settings
                    </h4>
                    <hr />

                    <div class="form-group">
                        <label class="col-md-2 control-label">Stripe Client ID</label>
                        <div class="col-md-10">
                            <input type="text" class="form-control" id="StripeClientID" name="StripeClientID" value="@Model.StripeClientID">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-2 control-label">Stripe Client Secret (Api Key)</label>
                        <div class="col-md-10">
                            <input type="text" class="form-control" id="StripeApiKey" name="StripeApiKey" value="@Model.StripeApiKey">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-2 control-label">Stripe Publishable Key</label>
                        <div class="col-md-10">
                            <input type="text" class="form-control" id="StripePublishableKey" name="StripePublishableKey" value="@Model.StripePublishableKey">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-offset-2 col-lg-10">
                            <button class="btn btn-primary" type="submit"><i class="fa fa-save"></i> Save</button>
                            <a href="@Url.Action("Plugins", "Plugin", new { area = "Admin" })" class="btn btn-default"><i class="fa fa-remove"></i> Cancel</a>
                        </div>
                    </div>

                </div>
            </div>
        </form>
    </div>

</div>

@section Scripts {    
    @Scripts.Render("~/bundles/jqueryval")
}

src/Plugins/Plugin.Payment.Stripe/Views/Payment.cshtml
@model BeYourMarket.Model.Models.Order

<div class="form-group">
    <form class="form" action="@Url.Action("Payment")" method="post" role="form">
        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="@CacheHelper.GetSettingDictionary(Plugin.Payment.Stripe.StripePlugin.SettingStripePublishableKey).Value"
                data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
                data-name="@CacheHelper.Settings.Name"
                data-description="@Model.Description"
                data-currency="@CacheHelper.Settings.Currency"
                data-amount="@Model.PriceInCents">

        </script>
    </form>
</div>

src/Plugins/Plugin.Payment.Stripe/Views/PaymentSetting.cshtml
@model Plugin.Payment.Stripe.StripePlugin.Enum_StripeConnectStatus
@{
    ViewBag.Title = "Payment Settings";
}

@Html.Partial("_UserMessage")

<p>
    To accept payments you need to connect your <a href="https://stripe.com" target="_blank">Stripe</a> account with products.
</p>

@if (Model == Plugin.Payment.Stripe.StripePlugin.Enum_StripeConnectStatus.None)
{
    <p>
        <a href="@CacheHelper.StripeConnectUrl" class="stripe-connect">
            <span>Connect with Stripe</span>
        </a>
    </p>
}
else
{
    <form action="@Url.Action("PaymentSettingDeauthorize")" method="post">
        <button class="stripe-connect">
            <span>Disconnect with Stripe</span>
        </button>
    </form>
}

@section Scripts {    
    @Scripts.Render("~/bundles/jqueryval")
}

src/Plugins/Plugin.Payment.Stripe/Views/Transaction.cshtml
@using GridMvc.Html
@using i18n
@using Microsoft.AspNet.Identity

@model Plugin.Payment.Stripe.Models.OrderTransactionModel

@{
    ViewBag.Title = "Transaction";
}

@section Styles {
    <link href="~/Content/Gridmvc.css" rel="stylesheet" />
    <link href="~/Content/gridmvc.datepicker.min.css" rel="stylesheet" />
}


@helper DisplayStatus(bool paid)
{
    if (paid)
    {
        <span class="label label-success">[[[Paid]]]</span>
    }
    else
    {
        <span class="label label-info">[[[Pending]]]</span>
    }   
}

@helper DisplayListing(string title, int ListingID)
{
    <a href="@Url.Action("Listing", "Listing", new { id = ListingID })">@title <i class="fa fa-external-link"></i></a>
}

<div class="panel-body">
    <h4><i class="fa fa-arrow-left"></i> Transaction (Income)</h4>
    <hr />

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            @Html.Grid(Model.TransactionPayment).SetLanguage(Context.GetPrincipalAppLanguageForRequest().ToString()).EmptyText("[[[There are no items to display.]]]").Columns(columns =>
                                       {
                                           columns.Add()
                                             .Encoded(false)
                                             .Sanitized(false)
                                             .RenderValueAs(x => DisplayStatus(x.IsCaptured));

                                           columns.Add(x => x.Created).Titled("Date").RenderValueAs(x => x.Created.ToShortDateString());
                                           columns.Add(x => x.Order.Description).Titled("Description");
                                           columns.Add(x => x.Order.PriceFormatted).Titled("Price");

                                       }).WithPaging(10).Selectable(false)
        </div>
    </div>

</div>

<div class="panel-body">
    <h4><i class="fa fa-arrow-right"></i> Transaction (Expense)</h4>
    <hr />

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            @Html.Grid(Model.TransactionPayout).SetLanguage(Context.GetPrincipalAppLanguageForRequest().ToString()).EmptyText("[[[There are no items to display.]]]").Columns(columns =>
                                       {
                                           columns.Add()
                                             .Encoded(false)
                                             .Sanitized(false)
                                             .RenderValueAs(x => DisplayStatus(x.IsCaptured));

                                           columns.Add(x => x.Created).Titled("Date").RenderValueAs(x => x.Created.ToShortDateString());
                                           columns.Add(x => x.Order.Description).Titled("Description");
                                           columns.Add(x => x.Order.PriceFormatted).Titled("Price");

                                       }).WithPaging(10).Selectable(false)
        </div>
    </div>

</div>



@section Scripts {
    <script src="~/Scripts/gridmvc.min.js"></script>    
    @Html.Partial("_LocalizationGridMvc")
}

src/Plugins/Plugin.Payment.Stripe/Views/TransactionOverview.cshtml
@using GridMvc.Html
@using i18n
@using Microsoft.AspNet.Identity

@model Plugin.Payment.Stripe.Models.OrderTransactionModel

@section Styles {
    <link href="~/Content/Gridmvc.css" rel="stylesheet" />
    <link href="~/Content/gridmvc.datepicker.min.css" rel="stylesheet" />
}


@helper DisplayStatus(bool paid)
{
    if (paid)
    {
        <span class="label label-success">Paid</span>
    }
    else
    {
        <span class="label label-info">Pending</span>
    }
}

<div class="panel-body">
    <h4><i class="fa fa-cc-stripe"></i> Stripe Transaction</h4>
    <hr />

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            @Html.Grid(Model.TransactionPayment).SetLanguage(Context.GetPrincipalAppLanguageForRequest().ToString()).EmptyText("[[[There are no items to display.]]]").Columns(columns =>
       {
           columns.Add()
             .Encoded(false)
             .Sanitized(false)
             .RenderValueAs(x => DisplayStatus(x.IsCaptured));

           columns.Add(x => x.Created).Titled("Date").RenderValueAs(x => x.Created.ToShortDateString());
           columns.Add(x => x.OrderID).Titled("OrderID");
           columns.Add(x => x.Order.Description).Titled("Description");
           columns.Add(x => x.Order.PriceFormatted).Titled("Price");

       }).WithPaging(10).Selectable(false)
        </div>
    </div>

</div>



@section Scripts {
    <script src="~/Scripts/gridmvc.min.js"></script>
    @Html.Partial("_LocalizationGridMvc")
}