src/BeYourMarket.Web/Areas/Admin/Controllers/ContentPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using BeYourMarket.Service;
using System.Threading.Tasks;
using BeYourMarket.Model.Models;
using Repository.Pattern.UnitOfWork;
using Newtonsoft.Json;
using BeYourMarket.Web.Extensions;
using BeYourMarket.Web.Models.Grids;
using BeYourMarket.Web.Models;
using BeYourMarket.Web.Utilities;
using ImageProcessor.Imaging.Formats;
using System.Drawing;
using ImageProcessor;
using System.IO;
using System.Text;
using BeYourMarket.Model.Enum;
using RestSharp;
using BeYourMarket.Web.Areas.Admin.Models;
using Postal;
using System.Net.Mail;
using System.Net;
using BeYourMarket.Service.Models;
using BeYourMarket.Core.Web;

namespace BeYourMarket.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class ContentPageController : Controller
    {
        #region Fields
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        private ApplicationRoleManager _roleManager;

        private readonly ISettingService _settingService;
        private readonly ISettingDictionaryService _settingDictionaryService;

        private readonly ICategoryService _categoryService;
        private readonly IListingService _listingService;

        private readonly ICustomFieldService _customFieldService;
        private readonly ICustomFieldCategoryService _customFieldCategoryService;

        private readonly IContentPageService _contentPageService;

        private readonly IOrderService _orderService;

        private readonly IEmailTemplateService _emailTemplateService;

        private readonly DataCacheService _dataCacheService;
        private readonly SqlDbService _sqlDbService;

        private readonly IUnitOfWorkAsync _unitOfWorkAsync;
        #endregion

        #region Properties
        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }
        #endregion

        #region Constructor
        public ContentPageController(
            IUnitOfWorkAsync unitOfWorkAsync,
            ISettingService settingService,
            ICategoryService categoryService,
            IListingService listingService,
            ICustomFieldService customFieldService,
            ICustomFieldCategoryService customFieldCategoryService,
            IContentPageService contentPageService,
            IOrderService orderService,
            ISettingDictionaryService settingDictionaryService,
            IEmailTemplateService emailTemplateService,
            DataCacheService dataCacheService,
            SqlDbService sqlDbService)
        {
            _settingService = settingService;
            _settingDictionaryService = settingDictionaryService;

            _categoryService = categoryService;
            _listingService = listingService;
            _customFieldService = customFieldService;
            _customFieldCategoryService = customFieldCategoryService;

            _orderService = orderService;            

            _emailTemplateService = emailTemplateService;
            _contentPageService = contentPageService;
            _unitOfWorkAsync = unitOfWorkAsync;
            _dataCacheService = dataCacheService;
            _sqlDbService = sqlDbService;
        }
        #endregion

        #region Methods
        public ActionResult ContentPages()
        {
            var grid = new ContentPagesGrid(_contentPageService.Queryable().OrderByDescending(x => x.Created));

            var model = new ContentPageModel()
            {
                Grid = grid
            };

            return View(model);
        }

        public async Task<ActionResult> ContentPageUpdate(int? id)
        {
            var userId = User.Identity.GetUserId();
            var user = await UserManager.FindByIdAsync(userId);

            var model = new ContentPage();

            if (!id.HasValue || id == 0)
            {
                model.Author = user.FullName;
            }
            else
            {
                model = await _contentPageService.FindAsync(id);
            }

            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> ContentPageUpdate(ContentPage contentPage)
        {
            var userId = User.Identity.GetUserId();

            if (contentPage.ID == 0)
            {
                contentPage.ObjectState = Repository.Pattern.Infrastructure.ObjectState.Added;
                contentPage.Created = DateTime.Now;
                contentPage.LastUpdated = DateTime.Now;

                var query = await _contentPageService.Query(x => x.Slug.ToLower() == contentPage.Slug.ToLower()).SelectAsync();
                if (query.Any())
                {
                    TempData[TempDataKeys.UserMessageAlertState] = "bg-danger";
                    TempData[TempDataKeys.UserMessage] = string.Format("[[[Slug {0} already exists]]]", contentPage.Slug);

                    return View(contentPage);
                }

                if (_contentPageService.Queryable().Any())
                {
                    contentPage.Ordering = _contentPageService.Queryable().Max(x => x.Ordering);
                }

                _contentPageService.Insert(contentPage);
            }
            else
            {
                var contentPageExisting = await _contentPageService.FindAsync(contentPage.ID);

                contentPageExisting.Title = contentPage.Title;
                contentPageExisting.Description = contentPage.Description;
                contentPageExisting.Slug = contentPage.Slug;
                contentPageExisting.Html = contentPage.Html;
                contentPageExisting.UserID = userId;
                contentPageExisting.Author = contentPage.Author;
                contentPageExisting.Published = contentPage.Published;

                contentPageExisting.ObjectState = Repository.Pattern.Infrastructure.ObjectState.Modified;
                contentPageExisting.LastUpdated = DateTime.Now;

                _contentPageService.Update(contentPageExisting);
            }

            await _unitOfWorkAsync.SaveChangesAsync();

            _dataCacheService.RemoveCachedItem(CacheKeys.ContentPages);

            return RedirectToAction("ContentPages");
        }
        #endregion
    }
}

src/BeYourMarket.Web/Areas/Admin/Views/ContentPage/ContentPageUpdate.cshtml
@model BeYourMarket.Model.Models.ContentPage

@{
    ViewBag.Title = "[[[Content Page Update]]]";
}

@section Styles {
    <script src="~/Scripts/ckeditor/styles.js"></script>
}

<div class="wraper container-fluid">

    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-heading"><h3 class="panel-title">[[[Content Page Update]]]</h3></div>
                <div class="panel-body">
                    <form action="@Url.Action("ContentPageUpdate", "ContentPage")" id="form0" method="post" class="form-horizontal" role="form">
                        @Html.ValidationSummary(true, string.Empty, new { @class = "alert alert-danger" })
                        @Html.Partial("_UserMessage")

                        <div class="form-group">
                            <label class="col-sm-2 control-label">ID</label>
                            <div class="col-sm-10">
                                <p class="form-control-static">@Model.ID</p>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-2 control-label">[[[Title]]]</label>
                            <div class="col-md-10">
                                <input type="text" class="form-control" id="Title" name="Title" value="@Model.Title" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-2 control-label">[[[Description]]]</label>
                            <div class="col-md-10">
                                <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-2 control-label">[[[Slug]]]</label>
                            <div class="col-md-10">
                                <input type="text" class="form-control" id="Slug" name="Slug" value="@Model.Slug" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-2 control-label">[[[Ordering]]]</label>
                            <div class="col-md-10">
                                <input type="number" class="form-control" id="Ordering" name="Ordering" value="@Model.Ordering" min="0" required>
                            </div>
                        </div>                        

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <label class="cr-styled">
                                    <input id="Published" name="Published" type="checkbox" value="true" checked="@Model.Published">
                                    <i class="fa"></i>
                                    [[[Published]]]
                                </label>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-2 control-label">Html</label>
                            <div class="col-md-10">                                
                                <textarea class="ckeditor" id="Html" name="Html" rows="10" required>@Model.Html</textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-lg-offset-2 col-lg-10">
                                <button class="btn btn-primary" type="submit"><i class="fa fa-save"></i> [[[Save]]]</button>
                                <a href="@Url.Action("Categories", "Listing")" class="btn btn-default"><i class="fa fa-remove"></i> [[[Cancel]]]</a>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>

    <script>
        $(document).ready(function () {
            // Refresh cache
            CKEDITOR.timestamp = '@DateTime.Now.Ticks';

            var roxyFileman = '/fileman/index.html';

            CKEDITOR.replace('Html', {
                filebrowserBrowseUrl: roxyFileman,
                filebrowserImageBrowseUrl: roxyFileman + '?type=image',
                removeDialogTabs: 'link:upload;image:upload'
            });
        })
    </script>
}

src/BeYourMarket.Web/Areas/Admin/Views/ContentPage/ContentPages.cshtml
@using GridMvc.Html
@model BeYourMarket.Web.Models.ContentPageModel

@section Styles {
    <link href="~/Content/Gridmvc.css" rel="stylesheet" />
    <link href="~/Content/gridmvc.datepicker.min.css" rel="stylesheet" />
}

@{
    ViewBag.Title = "[[[Content Pages]]]";
}

@helper DisplayUpdateLink(int id)
{
    <a class="btn btn-primary m-b-5" href="@Url.Action("ContentPageUpdate", "ContentPage", new { id = id })"><i class="fa fa-edit"></i> [[[Edit]]]</a>
}

<div class="wraper container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">[[[Content Pages]]]</h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-10">
                            <a class="btn btn-primary" href="@Url.Action("ContentPageUpdate", "ContentPage")"><i class="fa fa-plus"></i> [[[Add New]]]</a>
                        </div>
                    </div>

                    <hr />

                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            @Html.Grid(Model.Grid).SetLanguage(Context.GetPrincipalAppLanguageForRequest().ToString()).EmptyText("[[[There are no items to display.]]]").Columns(columns =>
                       {
                           columns.Add()
                             .Encoded(false)
                             .Sanitized(false)
                             .RenderValueAs(x => DisplayUpdateLink(x.ID));

                           columns.Add(x => x.ID);
                           columns.Add(x => x.Slug).Titled("[[[Slug]]]");
                           columns.Add(x => x.Title).Titled("[[[Title]]]");
                           columns.Add(x => x.Description).Titled("[[[Description]]]");
                           columns.Add(x => x.Author).Titled("[[[Author]]]");
                           columns.Add(x => x.Published).Titled("[[[Published]]]");
                           columns.Add(x => x.Created).RenderValueAs(x => x.Created.ToShortDateString()).Titled("[[[Created]]]");
                           columns.Add(x => x.LastUpdated).RenderValueAs(x => x.LastUpdated.ToShortDateString()).Titled("[[[Last Updated]]]");


                       }).Sortable().Filterable().WithPaging(10).Selectable(false)
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div> <!-- End Row -->



</div>

@section Scripts {
    <script src="~/Scripts/gridmvc.min.js"></script>
    @Html.Partial("_LocalizationGridMvc")
}